### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jonocarroll** [jonocarroll/mathpix#1]
- [x] request API key
- [x] test with trial API key
- [x] send request as per http://docs.mathpix.com/#introduction
- [x] retrieve response
- [x] insert to `rmarkdown`

http://mathpix.com/
